---
- hosts: perf-suites
  name: Deploying Debezium performance testsuite
  tasks:
    - name: Install openjdk17
      become: true
      dnf:
        name: java-17-openjdk-devel

    - name: Clone perf-suite
      git:
        repo: "{{ suite_repository }}"
        version: "{{ suite_branch }}"
        dest: "~/perf-suite"
        force: true